import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import About from "./About";
export const metadata = {
  title: "About",
  description: "Generated by create next app",
  alternates: {
    canonical: "abc",
    languages: {
      "en-US": "English",
    },
  },
};
const page = () => {
  return (
    <div>
      <About />
    </div>
  );
};

export default page;
