import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import BlogDetailContent from "./BlogDetailContent"

export const metadata = {
  title: "Blog Details",
  description: "Generated by create next app",
  alternates: {
    canonical: "abc",
    languages: {
      "en-US": "English",
    },
  },
};
const page = () => {
  return (
    <div>
      <BlogDetailContent/>
    </div>
  );
};

export default page;
