import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";

import Project from "./type/[id]/page";
import Script from "next/script";

export const metadata = {
  title: "Projects",
  description: "Generated by create next app",
  alternates: {
    canonical: "abc",
    languages: {
      "en-US": "English"
    }
  }
};
const page = () => {
  return (
    <div>
      <Project />
    </div>
  );
};

export default page;
