import Homepage from "./homepage/page";
// import "react-notifications-component/dist/theme.css";

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app"
};

export default function Home() {
  return (
    <div>
      <Homepage />
    </div>
  );
}
