import Homepage from "./homepage/page";
import "bootstrap/dist/css/bootstrap.min.css";
// import "react-notifications-component/dist/theme.css";

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app"
};

export default function Home() {
  return (
    <div className="home">
      <Homepage />
    </div>
  );
}
