import Homepage from "./homepage/page";
import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="home">
      <Homepage></Homepage>
    </div>
  );
}
