import React from "react";
import Career from "./Career";
// @ts-ignore
import HeroSection from "@/components/About/HeroSection";

export const metadata = {
  title: "Career",
  description: "Generated by create next app",
  alternates: {
    canonical: "abc",
    languages: {
      "en-US": "English",
    },
  },
};
const page = () => {
  return (
    <div>
      <HeroSection
        title="Join our Team"
        text="Career"
        backgroundImage="../../career.png"
        color={"#fff"}
        background={"#fff"}
      />
      <Career />
    </div>
  );
};

export default page;
