import GetInTouch from "./GetInTouch";

export const metadata = {
  title: "Get In touch",
  description: "Generated by create next app",
  alternates: {
    canonical: "abc",
    languages: {
      "en-US": "English",
    },
  },
};
const page = () => {
  return (
    <>
      <GetInTouch />

    </>
  );
};

export default page;
