import React from 'react'
import 'bootstrap/dist/css/bootstrap.min.css';
import Privacy from "./Privacy"



export const metadata = {
  title: "Privacy",
  description: "Generated by create next app",
  alternates:{
    canonical:"abc",
    languages:{
      "en-US":"English"
    }
  },
  
};
const page = () => {
  return (
    <div>
      <Privacy/>
      
      
    </div>
  )
}

export default page